export const og_seo = {
  title: 'Agri-Flow',
  description: 'Community and blog of nature',
  locate: 'Thailand',
  tabimage: '/images/png/logo-with-circle-bg.png',
  url: 'https://agri-flow-client.vercel.app/',
  image: '/images/png/logo-with-circle-bg.png',
  width: '500',
  height: '500',
  site_name: 'Agri Flow',
  locale: 'th_TH',
  locale_alternate: 'en_US',
  keywords: 'nature, blog, community, communicate, group, social media',
  author: 'Ryoneme2',
  copyright: 'Copyright © 2022 by AgriFlow',
  robots: 'index,follow,noodp',
  googlebot: '',
  google: '',
  google_site_verification: '',
};
